spring.application.name=e7gzly
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5432/ehgezly_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect